[workspace]
resolver = "2"
members = [
    ".",
    "./derive",
]

[package]
name = "typescript-type-def"
version = "0.1.0"
authors = ["Daniel Beckwith <djbsnx@gmail.com>"]
edition = "2018"

[dependencies]
typescript-type-def-derive = { path = "./derive" }
serde = "1.0.126"

[dev-dependencies]
serde = { version = "1.0.126", features = ["derive"] }
serde_json = "1.0.64"

# TODO: fix and re-enable test
[[test]]
name = "test"
path = "tests/test.rs"
test = false
