[workspace]
resolver = "2"
members = [
    ".",
    "./derive",
]

[package]
name = "typescript-type-def"
version = "0.1.0"
authors = ["Daniel Beckwith <djbsnx@gmail.com>"]
edition = "2018"

[dependencies]
typescript-type-def-derive = { path = "./derive" }
serde = "1.0.123"

[dev-dependencies]
serde = { version = "1.0.123", features = ["derive"] }
serde_json = "1.0.62"
