[package]
name = "typescript-type-def-derive"
version = "0.1.0"
authors = ["Daniel Beckwith <djbsnx@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
darling = "0.13.0"
heck = "0.3.3"
proc-macro-error = "1.0.4"
proc-macro2 = "1.0.27"
quote = "1.0.9"
syn = { version = "1.0.72", default_features = false }
